# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390f487b3873ccc72d172d117ef9642f09c7b21a2536083ce78a000e06a0dbed6c24a450cb22b23465be51834f3a62583769e521b9848dbe8eded7e3aa1b7cf7

test:
  secret_key_base: 295a5f33b2f75cf08ba4e170101ff520b16acaef7a153f8830ee43b23b7cdc1654fdaf8f2f460ca6c42ece4b2a05c7e6220e03f72e81f4391e7cf4a1c864de67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
